version: 0.2

env:
  parameter-store:
    USERNAME: /myapp/docker-credentials/username
    PASSWORD: /myapp/docker-credentials/password
    KEY: /myapp/api/key

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - node --version
      - echo "Installed Node.js"
  
  pre_build:
    commands:
      - cd DevOps-Project-21 || exit 1
      - ls -lah  # Debugging step to verify files exist
      - npm install
      - echo "Dependencies installed"
  
  build:
    commands:
      
      - docker build . -t kantin10/netflix-react-app:latest --build-arg TMDB_V3_API_KEY=$KEY
  
  post_build:
    commands:
      - echo "Build completed, logging into DockerHub..."
      - docker login -u $USERNAME -p $PASSWORD
      - docker push kantin10/netflix-react-app:latest

artifacts:
  files:
    - '**/*'
  base-directory: "./DevOps-Project-21"
  name: build-artifact-name
  discard-paths: no
